#!/usr/bin/env ruby

# ssh into each hosts and ensure that acme.json is present

hosts = ENV["KAMAL_HOSTS"].split(",")

hosts.each do |ip|
  destination = "root@#{ip}"
  puts "Creating /letsencrypt/acme.json on #{destination}"
  `ssh #{destination} "mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json"`
end
